<?php /* @var $this Neklo_Instagram_Block_Widget_Feed */ ?>
<?php if ($this->canShow()): ?>
    <?php $imageList = $this->getImageList(); ?>
    <?php if (count($imageList)) : ?>
        <div class="neklo-instagram">
                <script>
                    resizeInstaImage = function(element) {
                        var w = jQuery(element).width();
                        var h = jQuery(element).height();
                        if (w > h) {
                            jQuery(element).css({
                                width: 'auto',
                                height: '100%'
                            })
                        } else {
                            jQuery(element).css({
                                height: 'auto',
                                width: '100%'
                            })
                        }
                        console.log([
                            jQuery(element).width(),
                            jQuery(element).height()
                        ]);
                    }
                </script>
            <?php if ($this->getTitle()) : ?>
                <div class="neklo-instagram-title">
                    <span><?php echo $this->escapeHtml($this->getTitle()) ?></span>
                </div>
            <?php endif; ?>
            <?php if ($this->getDescription()) : ?>
                <div class="neklo-instagram-description">
                    <span><?php echo nl2br($this->escapeHtml($this->getDescription())) ?></span>
                </div>
            <?php endif; ?>
            <ul class="neklo-instagram-list">
                <?php foreach ($imageList as $image) : ?>
                    <li>
                        <a href="<?php echo $image->getLink(); ?>" target="_blank" >
                            <i class="neklo-instagram-over"></i>
                            <div class="neklo-instagram-image-wrap" style="position: relative;overflow: hidden;width:<?php echo intval($this->getImageWidth()) ?>px; height:<?php echo intval($this->getImageHeight()) ?>px;">
                            <img style="position: absolute; top: -9999px; bottom: -9999px; left: -9999px; right: -9999px; margin: auto;" src="<?php echo $image->getUrl(); ?>" alt="<?php echo $this->escapeHtml($image->getName()); ?>" title="<?php echo $this->escapeHtml($image->getName()); ?>" onload="resizeInstaImage(this)" />
                            </div>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
<?php endif; ?>
