<?php
/**
 * {{Esparkinfo}}_{{Imageuploader}} extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       {{Esparkinfo}}
 * @package        {{Esparkinfo}}_{{Imageuploader}}
 * @copyright      Copyright (c) 2018
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Imageupload view widget template
 *
 * @category    Esparkinfo
 * @package     Esparkinfo_Imageuploader
 * @author      Ultimate Module Creator
 */
?>
<?php $_imageupload = $this->getCurrentImageupload();?>
<?php if ($_imageupload) :?>
    <div class="imageupload-widget-view">
        <h3><?php echo $_imageupload->getImageupload()?></h3>
        <div>
            <div class="imageupload-widget">
                <?php echo Mage::helper('esparkinfo_imageuploader')->__('imageupload');?>:<?php echo $_imageupload->getImageupload();?>
            </div>

        </div>
    </div>
<?php endif;?>
